title: Вила Биляна
email: bilyanamail@example.com
phone: +359 888 888 888
description: Почивка в Сърбия
destination: docs
baseurl: "/villabilyana"  
url: ""
external_url: "https://www.facebook.com/Babin-zub-vili-Bilyana-949065918483697/"


# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - docs
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js
  - theme-personal
